[features]
seeds = false
skip-lint = false
[programs.localnet]
pdas = "8q4D16QCFu4ViefovpsqGRsneboCzfNnbFA2KVefueqH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/justin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
